
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'

Documentation:
  Enabled: false

IndentationConsistency:
  EnforcedStyle: 'indented_internal_methods'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
